#ifndef QUEUE_ERRORS_H
#define QUEUE_ERRORS_H

enum ERRORS {ARGUMENTS_ERROR = 1,
    CFG_FILE_OPEN_ERROR = 2,
    CFG_FILE_READ_ERROR = 3,
    TXT_FILE_READ_ERROR = 4,
    RESULT_FILE_OPEN_ERROR = 5,
    RESULT_WRITING_ERROR = 6,
    INDEXING_PATH_ERROR = 7
    };

#endif //QUEUE_ERRORS_H
